---
- name: configure ufw
  community.general.ufw:
    rule: allow
    port: "{{ sockd_bind_port }}"
    proto: tcp
    state: enabled
    comment: "Dante Socks5 Proxy"
  changed_when: False
  ignore_errors: True
  notify: reload ufw
  become: true
  when:
    - "'active' in ufw_status.stdout"
    - ansible_os_family == 'Debian'

- name: configure firewalld
  ansible.posix.firewalld:
    port: "{{ sockd_bind_port }}/tcp"
    permanent: yes
    state: enabled
  changed_when: False
  ignore_errors: True
  notify: reload firewalld
  become: true
  when:
    - "'running' in firewalld_status.stdout"
    - ansible_os_family == 'RedHat'